In [1]:
#this is only for colab do not run

import os
from google.colab import drive
MOUNTPOINT = '/content/gdrive'
DATADIR = os.path.join(MOUNTPOINT, 'My Drive', 'myfolder')
drive.mount(MOUNTPOINT)

Mounted at /content/gdrive


In [2]:
#importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [3]:
# loading data
#for colab
df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/insurance.csv')
#run this (change path)
# df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/insurance.csv')
df.shape

(1338, 7)

In [4]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [8]:
#Checking for null values

df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [20]:
# encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#sex
df['sex'] = le.fit_transform(df['sex'])

# smoker or not
df['smoker'] = le.fit_transform(df['smoker'])

#region
df['region'] = le.fit_transform(df['region'])


In [21]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [22]:
#split

x=df.drop(['charges'],axis=1)
y=df.charges

In [23]:
x

age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
1333   50    1  30.970         3       0       1
1334   18    0  31.920         0       0       0
1335   18    0  36.850         0       0       2
1336   21    0  25.800         0       0       3
1337   61    0  29.070         0       1       1

[1338 rows x 6 columns]

In [24]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [25]:
x = df.drop(['charges'],axis=1)
y = df['charges']

In [26]:
# Train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [27]:
x_train

age  sex     bmi  children  smoker  region
559    19    1  35.530         0       0       1
273    50    1  27.455         1       0       0
471    18    0  30.115         0       0       0
22     18    1  34.100         0       0       2
939    53    1  29.480         0       0       2
...   ...  ...     ...       ...     ...     ...
1180   42    0  41.325         1       0       0
1147   20    0  31.920         0       0       1
527    51    0  25.800         1       0       3
1149   42    1  34.100         0       0       3
1289   44    1  34.320         1       0       2

[1070 rows x 6 columns]

In [28]:
x_test

age  sex     bmi  children  smoker  region
7      37    0  27.740         3       0       1
999    36    0  26.885         0       0       1
1209   59    1  37.100         1       0       3
491    61    0  25.080         0       0       2
625    29    0  26.030         0       0       1
...   ...  ...     ...       ...     ...     ...
271    50    1  34.200         2       1       3
695    26    0  40.185         0       0       1
1039   19    1  27.265         2       0       1
323    57    1  40.945         0       0       0
835    42    1  35.970         2       0       2

[268 rows x 6 columns]

In [29]:
y_train

559     1646.42970
273     9617.66245
471     2203.47185
22      1137.01100
939     9487.64420
           ...    
1180    7650.77375
1147    2261.56880
527     9861.02500
1149    5979.73100
1289    7147.47280
Name: charges, Length: 1070, dtype: float64

In [30]:
y_test

7        7281.50560
999      5267.81815
1209    12347.17200
491     24513.09126
625      3736.46470
           ...     
271     42856.83800
695      3201.24515
1039    22493.65964
323     11566.30055
835      7160.33030
Name: charges, Length: 268, dtype: float64

In [31]:
# LR

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

lr=LinearRegression()
lr.fit(x_train,y_train)
x_train_predict=lr.predict(x_train)
x_test_predict=lr.predict(x_test)
print(lr.score(x_train, y_train))
print(lr.score(x_test,y_test))


0.7633895728397835
0.6957010622294885


In [32]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
train_Score=r2_score(y_train,x_train_predict)
train_Score

0.7633895728397835

In [33]:
test_score=r2_score(y_test,x_test_predict)
test_score

0.6957010622294885

In [34]:
# RandomForest

from sklearn.ensemble import RandomForestRegressor

rfr=RandomForestRegressor()
rfr.fit(x_train,y_train)
prediction=rfr.predict(x_test)

print(rfr.score(x_test,y_test))
print(rfr.score(x_train,y_train))

0.8087758328729702
0.9781563301423893


In [35]:
from sklearn.metrics import r2_score
r2_score(y_test,prediction)

0.8087758328729702

In [36]:
# SVM

from sklearn.svm import SVR

svm = SVR()
svm.fit(x_train,y_train)
prediction = svm.predict(x_test)

r2_score(y_test,prediction)


-0.13111283725342893

In [39]:
#prediction
rfr.predict([[19,0,27.9,0,1,3]])

array([16966.9126908])

In [40]:
lr.predict([[19,0,27.9,0,1,3]])

array([25358.9283003])

In [41]:
svm.predict([[19,0,27.9,0,1,3]])

array([9095.69072296])

In [ ]:
#do not save just skip saving part
# max accu. in randomforest therefore using rfr

In [ ]:
#saving model

import joblib
joblib.dump(rfr,'model_joblib_test')
rfr = joblib.load('model_joblib_test')

In [ ]:
#Run gui check if changes and send SS of Output (good ones)

In [ ]:
#GUI
from tkinter import *

In [ ]:
import joblib

In [42]:
def show_entry():
    
    p1 = float(e1.get())
    p2 = float(e2.get())
    p3 = float(e3.get())
    p4 = float(e4.get())
    p5 = float(e5.get())
    p6 = float(e6.get())

    # If model saved 
    # model = joblib.load('model_joblib_gr')
    
    # If not saved
    model=rfr
    result = model.predict([[p1,p2,p3,p4,p5,p6]])
    
    Label(master, text = "Insurance Cost").grid(row=7)
    Label(master, text=result).grid(row=8)


master =Tk()
master.title("Insurance Cost Prediction")
label = Label(master,text = "Insurance Cost Prediction",bg = "black",
               fg = "white").grid(row=0,columnspan=2)

Label(master,text = "Enter Your Age").grid(row=1)
Label(master,text = "Male Or Female [1/0]").grid(row=2)
Label(master,text = "Enter Your BMI Value").grid(row=3)
Label(master,text = "Enter Number of Children").grid(row=4)
Label(master,text = "Smoker Yes/No [1/0]").grid(row=5)
Label(master,text = "Region [1-4]").grid(row=6)


e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e6 = Entry(master)



e1.grid(row=1,column=1)
e2.grid(row=2,column=1)
e3.grid(row=3,column=1)
e4.grid(row=4,column=1)
e5.grid(row=5,column=1)
e6.grid(row=6,column=1)


Button(master,text="Predict",command=show_entry).grid()

mainloop()

NameError: ignored